/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppNewsRouteImport } from './routes/app.news'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as TeamShellRouteImport } from './routes/team/_shell'
import { Route as TeamLoginRouteImport } from './routes/team/login'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as AdminShellAnalyticsRouteImport } from './routes/admin/_shell/analytics'
import { Route as AdminShellChatsRouteImport } from './routes/admin/_shell/chats'
import { Route as AdminShellNewsRouteImport } from './routes/admin/_shell/news'
import { Route as AdminShellRequestsRouteImport } from './routes/admin/_shell/requests'
import { Route as AdminShellTeamRouteImport } from './routes/admin/_shell/team'
import { Route as AdminShellUsersRouteImport } from './routes/admin/_shell/users'
import { Route as AppChatsIndexRouteImport } from './routes/app.chats.index'
import { Route as AppChatsRequestIdRouteImport } from './routes/app.chats.$requestId'
import { Route as TeamShellIndexRouteImport } from './routes/team/_shell/index'
import { Route as TeamShellDocumentsRouteImport } from './routes/team/_shell/documents'
import { Route as TeamShellNotificationsRouteImport } from './routes/team/_shell/notifications'
import { Route as TeamShellProfileRouteImport } from './routes/team/_shell/profile'
import { Route as TeamShellProgressRouteImport } from './routes/team/_shell/progress'
import { Route as TeamShellWorkRouteImport } from './routes/team/_shell/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const TeamShellRoute = TeamShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => TeamRoute,
} as any)
const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TeamRoute,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAnalyticsRoute = AdminShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellChatsRoute = AdminShellChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellNewsRoute = AdminShellNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellRequestsRoute = AdminShellRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellTeamRoute = AdminShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellUsersRoute = AdminShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminShellRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRequestIdRoute = AppChatsRequestIdRouteImport.update({
  id: '/chats/$requestId',
  path: '/chats/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const TeamShellIndexRoute = TeamShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamShellRoute,
} as any)
const TeamShellDocumentsRoute = TeamShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => TeamShellRoute,
} as any)
const TeamShellNotificationsRoute = TeamShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeamShellRoute,
} as any)
const TeamShellProfileRoute = TeamShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeamShellRoute,
} as any)
const TeamShellProgressRoute = TeamShellProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TeamShellRoute,
} as any)
const TeamShellWorkRoute = TeamShellWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => TeamShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/news': typeof AppNewsRoute
  '/app/profile': typeof AppProfileRoute
  '/team/login': typeof TeamLoginRoute
  '/app/': typeof AppIndexRoute
  '/admin/analytics': typeof AdminShellAnalyticsRoute
  '/admin/chats': typeof AdminShellChatsRoute
  '/admin/news': typeof AdminShellNewsRoute
  '/admin/requests': typeof AdminShellRequestsRoute
  '/admin/team': typeof AdminShellTeamRoute
  '/admin/users': typeof AdminShellUsersRoute
  '/app/chats/$requestId': typeof AppChatsRequestIdRoute
  '/team/documents': typeof TeamShellDocumentsRoute
  '/team/notifications': typeof TeamShellNotificationsRoute
  '/team/profile': typeof TeamShellProfileRoute
  '/team/progress': typeof TeamShellProgressRoute
  '/team/work': typeof TeamShellWorkRoute
  '/admin/': typeof AdminShellIndexRoute
  '/app/chats/': typeof AppChatsIndexRoute
  '/team/': typeof TeamShellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminShellIndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/team': typeof TeamShellIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/news': typeof AppNewsRoute
  '/app/profile': typeof AppProfileRoute
  '/team/login': typeof TeamLoginRoute
  '/app': typeof AppIndexRoute
  '/admin/analytics': typeof AdminShellAnalyticsRoute
  '/admin/chats': typeof AdminShellChatsRoute
  '/admin/news': typeof AdminShellNewsRoute
  '/admin/requests': typeof AdminShellRequestsRoute
  '/admin/team': typeof AdminShellTeamRoute
  '/admin/users': typeof AdminShellUsersRoute
  '/app/chats/$requestId': typeof AppChatsRequestIdRoute
  '/team/documents': typeof TeamShellDocumentsRoute
  '/team/notifications': typeof TeamShellNotificationsRoute
  '/team/profile': typeof TeamShellProfileRoute
  '/team/progress': typeof TeamShellProgressRoute
  '/team/work': typeof TeamShellWorkRoute
  '/app/chats': typeof AppChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/news': typeof AppNewsRoute
  '/app/profile': typeof AppProfileRoute
  '/team/_shell': typeof TeamShellRouteWithChildren
  '/team/login': typeof TeamLoginRoute
  '/app/': typeof AppIndexRoute
  '/admin/_shell/analytics': typeof AdminShellAnalyticsRoute
  '/admin/_shell/chats': typeof AdminShellChatsRoute
  '/admin/_shell/news': typeof AdminShellNewsRoute
  '/admin/_shell/requests': typeof AdminShellRequestsRoute
  '/admin/_shell/team': typeof AdminShellTeamRoute
  '/admin/_shell/users': typeof AdminShellUsersRoute
  '/app/chats/$requestId': typeof AppChatsRequestIdRoute
  '/team/_shell/documents': typeof TeamShellDocumentsRoute
  '/team/_shell/notifications': typeof TeamShellNotificationsRoute
  '/team/_shell/profile': typeof TeamShellProfileRoute
  '/team/_shell/progress': typeof TeamShellProgressRoute
  '/team/_shell/work': typeof TeamShellWorkRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/app/chats/': typeof AppChatsIndexRoute
  '/team/_shell/': typeof TeamShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/team'
    | '/admin/login'
    | '/app/documents'
    | '/app/news'
    | '/app/profile'
    | '/team/login'
    | '/app/'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/news'
    | '/admin/requests'
    | '/admin/team'
    | '/admin/users'
    | '/app/chats/$requestId'
    | '/team/documents'
    | '/team/notifications'
    | '/team/profile'
    | '/team/progress'
    | '/team/work'
    | '/admin/'
    | '/app/chats/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/team'
    | '/admin/login'
    | '/app/documents'
    | '/app/news'
    | '/app/profile'
    | '/team/login'
    | '/app'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/news'
    | '/admin/requests'
    | '/admin/team'
    | '/admin/users'
    | '/app/chats/$requestId'
    | '/team/documents'
    | '/team/notifications'
    | '/team/profile'
    | '/team/progress'
    | '/team/work'
    | '/app/chats'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/team'
    | '/admin/_shell'
    | '/admin/login'
    | '/app/documents'
    | '/app/news'
    | '/app/profile'
    | '/team/_shell'
    | '/team/login'
    | '/app/'
    | '/admin/_shell/analytics'
    | '/admin/_shell/chats'
    | '/admin/_shell/news'
    | '/admin/_shell/requests'
    | '/admin/_shell/team'
    | '/admin/_shell/users'
    | '/app/chats/$requestId'
    | '/team/_shell/documents'
    | '/team/_shell/notifications'
    | '/team/_shell/profile'
    | '/team/_shell/progress'
    | '/team/_shell/work'
    | '/admin/_shell/'
    | '/app/chats/'
    | '/team/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  TeamRoute: typeof TeamRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/team/_shell': {
      id: '/team/_shell'
      path: ''
      fullPath: '/team'
      preLoaderRoute: typeof TeamShellRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/login': {
      id: '/team/login'
      path: '/login'
      fullPath: '/team/login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof TeamRoute
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/analytics': {
      id: '/admin/_shell/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminShellAnalyticsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/chats': {
      id: '/admin/_shell/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminShellChatsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/news': {
      id: '/admin/_shell/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminShellNewsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/requests': {
      id: '/admin/_shell/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminShellRequestsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/team': {
      id: '/admin/_shell/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminShellTeamRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/users': {
      id: '/admin/_shell/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminShellUsersRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/app/chats/': {
      id: '/app/chats/'
      path: '/chats'
      fullPath: '/app/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/$requestId': {
      id: '/app/chats/$requestId'
      path: '/chats/$requestId'
      fullPath: '/app/chats/$requestId'
      preLoaderRoute: typeof AppChatsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/team/_shell/': {
      id: '/team/_shell/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamShellIndexRouteImport
      parentRoute: typeof TeamShellRoute
    }
    '/team/_shell/documents': {
      id: '/team/_shell/documents'
      path: '/documents'
      fullPath: '/team/documents'
      preLoaderRoute: typeof TeamShellDocumentsRouteImport
      parentRoute: typeof TeamShellRoute
    }
    '/team/_shell/notifications': {
      id: '/team/_shell/notifications'
      path: '/notifications'
      fullPath: '/team/notifications'
      preLoaderRoute: typeof TeamShellNotificationsRouteImport
      parentRoute: typeof TeamShellRoute
    }
    '/team/_shell/profile': {
      id: '/team/_shell/profile'
      path: '/profile'
      fullPath: '/team/profile'
      preLoaderRoute: typeof TeamShellProfileRouteImport
      parentRoute: typeof TeamShellRoute
    }
    '/team/_shell/progress': {
      id: '/team/_shell/progress'
      path: '/progress'
      fullPath: '/team/progress'
      preLoaderRoute: typeof TeamShellProgressRouteImport
      parentRoute: typeof TeamShellRoute
    }
    '/team/_shell/work': {
      id: '/team/_shell/work'
      path: '/work'
      fullPath: '/team/work'
      preLoaderRoute: typeof TeamShellWorkRouteImport
      parentRoute: typeof TeamShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellAnalyticsRoute: typeof AdminShellAnalyticsRoute
  AdminShellChatsRoute: typeof AdminShellChatsRoute
  AdminShellNewsRoute: typeof AdminShellNewsRoute
  AdminShellRequestsRoute: typeof AdminShellRequestsRoute
  AdminShellTeamRoute: typeof AdminShellTeamRoute
  AdminShellUsersRoute: typeof AdminShellUsersRoute
  AdminShellIndexRoute: typeof AdminShellIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAnalyticsRoute: AdminShellAnalyticsRoute,
  AdminShellChatsRoute: AdminShellChatsRoute,
  AdminShellNewsRoute: AdminShellNewsRoute,
  AdminShellRequestsRoute: AdminShellRequestsRoute,
  AdminShellTeamRoute: AdminShellTeamRoute,
  AdminShellUsersRoute: AdminShellUsersRoute,
  AdminShellIndexRoute: AdminShellIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface AdminRouteChildren {
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNewsRoute: typeof AppNewsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatsRequestIdRoute: typeof AppChatsRequestIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppNewsRoute: AppNewsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsRequestIdRoute: AppChatsRequestIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TeamShellRouteChildren {
  TeamShellDocumentsRoute: typeof TeamShellDocumentsRoute
  TeamShellNotificationsRoute: typeof TeamShellNotificationsRoute
  TeamShellProfileRoute: typeof TeamShellProfileRoute
  TeamShellProgressRoute: typeof TeamShellProgressRoute
  TeamShellWorkRoute: typeof TeamShellWorkRoute
  TeamShellIndexRoute: typeof TeamShellIndexRoute
}

const TeamShellRouteChildren: TeamShellRouteChildren = {
  TeamShellDocumentsRoute: TeamShellDocumentsRoute,
  TeamShellNotificationsRoute: TeamShellNotificationsRoute,
  TeamShellProfileRoute: TeamShellProfileRoute,
  TeamShellProgressRoute: TeamShellProgressRoute,
  TeamShellWorkRoute: TeamShellWorkRoute,
  TeamShellIndexRoute: TeamShellIndexRoute,
}

const TeamShellRouteWithChildren = TeamShellRoute._addFileChildren(
  TeamShellRouteChildren,
)

interface TeamRouteChildren {
  TeamShellRoute: typeof TeamShellRouteWithChildren
  TeamLoginRoute: typeof TeamLoginRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamShellRoute: TeamShellRouteWithChildren,
  TeamLoginRoute: TeamLoginRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  TeamRoute: TeamRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
